# Generated by Django 4.1.3 on 2023-05-10 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_imovel', models.CharField(choices=[('CS', 'Casa'), ('AP', 'Apartamento'), ('TR', 'Terreno'), ('GL', 'Galpão'), ('IN', 'Industria'), ('RU', 'Rural')], max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=256)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aluguel', models.BooleanField(default=False)),
                ('compra', models.BooleanField(default=False)),
                ('venda', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=20)),
                ('numeroquartos', models.IntegerField(null=True)),
                ('numerobanheiros', models.IntegerField(null=True)),
                ('vagasgaragem', models.IntegerField(null=True)),
                ('areatotal', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('areaconstruida', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_disponivel', models.DateTimeField()),
                ('foto_capa', models.ImageField(blank=True, upload_to='album/%m/%Y/')),
                ('ativo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Imóveis',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, upload_to='album/%m/%Y/')),
                ('id_imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.properties')),
            ],
            options={
                'verbose_name_plural': 'Álbuns',
            },
        ),
    ]
