# Generated by Django 4.1.3 on 2023-02-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='imovel',
            new_name='id_imovel',
        ),
        migrations.RenameField(
            model_name='properties',
            old_name='usuario',
            new_name='id_usuario',
        ),
        migrations.AddField(
            model_name='properties',
            name='foto_capa',
            field=models.ImageField(blank=True, upload_to='album/%m/%Y/'),
        ),
        migrations.AddField(
            model_name='properties',
            name='vagasgaragem',
            field=models.IntegerField(null=True),
        ),
    ]
