# Generated by Django 4.1.3 on 2023-02-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_rename_imovel_album_id_imovel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='properties',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
    ]
