# Generated by Django 4.1.3 on 2022-11-19 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('ativo', models.BooleanField()),
                ('observacao', models.TextField()),
                ('data_cadastro', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2)),
                ('ativo', models.BooleanField()),
                ('nomecliente', models.CharField(max_length=256)),
                ('cpf_cnjp', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=256)),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=256)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('observacao', models.TextField()),
                ('data_cadastro', models.DateTimeField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.category')),
            ],
        ),
    ]
