# Generated by Django 4.1.3 on 2023-01-10 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0004_client_aluguel_client_compra_client_venda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='anexo',
            field=models.ImageField(blank=True, upload_to='anexo/%m/%Y/'),
        ),
        migrations.AddField(
            model_name='client',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
