# Generated by Django 4.1.3 on 2023-05-10 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=256)),
                ('anexo', models.ImageField(blank=True, upload_to='anexo/%m/%Y/')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_operacao', models.DateTimeField()),
                ('tipo_operacao', models.CharField(choices=[('ENT', 'Entrada'), ('SAI', 'Saída')], max_length=3)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Operações',
            },
        ),
    ]
