# Generated by Django 4.1.3 on 2022-11-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=256)),
                ('anexo', models.ImageField(blank=True, upload_to='anexo/%m/%Y/')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_operacao', models.DateTimeField()),
                ('tipo_operacao', models.CharField(choices=[('ENT', 'Entrada'), ('SAI', 'Saída')], max_length=3)),
            ],
        ),
    ]
